<Project Sdk="Aspire.AppHost.Sdk/13.4.6">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>3ec5940f-40a3-4605-b5ac-66da44782d18</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.Azure.AppService" Version="13.4.6" />
    <PackageReference Include="Aspire.Hosting.Azure.CognitiveServices" Version="13.4.6" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AspireWithOpenAI.ApiService\AspireWithOpenAI.ApiService.csproj" />
    <ProjectReference Include="..\AspireWithOpenAI.Web\AspireWithOpenAI.Web.csproj" />
  </ItemGroup>

</Project>
